### ISSUE TITLE
idea for banlogs & reportlogs

### ISSUE THREAD

**Issue by drkuze** [JayXTQ/DiscordLab#2]
- banlogs | ground, user name, user name by team, duration
- reportlogs | Reporter, Reported, Reason, UTC Time

**Comment by JayXTQ** [comment]
This can be done by AdvancedLogging, but maybe there should be some sort of moderation log module too, yes

**Comment by JayXTQ** [comment]
https://github.com/JayXTQ/DiscordLab/releases/tag/1.0.0.M
