### ISSUE TITLE
[FEATURE] - ban & unban command system that only staff role can use

### ISSUE THREAD

**Issue by drkuze** [JayXTQ/DiscordLab#5]
### Before continuing...

- [X] I have searched the existing issues
- [X] I have checked the README

### Describe alternatives you've considered

ban & unban command system that only staff role can use

**command:**
`/ban`
`/unban`

**Comment by JayXTQ** [comment]
Added to my to-do list

**Comment by JayXTQ** [comment]
https://github.com/JayXTQ/DiscordLab/releases/tag/1.0.0.M
